version: '3.7'

services:
  readyscript: &readyscript
    build: &build
      context: ./docker
      dockerfile: Dockerfile
      args:
        readyscript_version: 6
    networks:
      readyscript_net:
        ipv4_address: 172.16.18.10
    volumes:
      - ./begateway:/var/www/html/modules/begateway
    extra_hosts:
      - "readyscript.local:172.16.18.10"
    depends_on:
      - mysql
    ports:
      - 80:8080
    cap_add:
      - NET_ADMIN
    tty: true

  mysql:
    image: mysql:5.6
    restart: always
    networks:
      readyscript_net:
        ipv4_address: 172.16.18.20
    volumes:
      - /var/lib/mysql
      - ./docker/etc/mysql/mysql.conf.d/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: readyscript

networks:
  readyscript_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.18.0/24"
